//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string DisplayOrder { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
